/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CertificatesCodeRouteImport } from './routes/certificates.$code'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as ApiPublicWebhooksUddoktapayRouteImport } from './routes/api/public/webhooks.uddoktapay'
import { Route as AuthenticatedLearnSlugLessonIdRouteImport } from './routes/_authenticated/learn.$slug.$lessonId'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin.courses.$id'

const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCodeRoute = CertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksUddoktapayRoute =
  ApiPublicWebhooksUddoktapayRouteImport.update({
    id: '/api/public/webhooks/uddoktapay',
    path: '/api/public/webhooks/uddoktapay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLearnSlugLessonIdRoute =
  AuthenticatedLearnSlugLessonIdRouteImport.update({
    id: '/learn/$slug/$lessonId',
    path: '/learn/$slug/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/learn/$slug/$lessonId': typeof AuthenticatedLearnSlugLessonIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/learn/$slug/$lessonId': typeof AuthenticatedLearnSlugLessonIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/_authenticated/learn/$slug/$lessonId': typeof AuthenticatedLearnSlugLessonIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/admin'
    | '/dashboard'
    | '/certificates/$code'
    | '/checkout/return'
    | '/courses/$slug'
    | '/admin/orders'
    | '/admin/courses/$id'
    | '/learn/$slug/$lessonId'
    | '/api/public/webhooks/uddoktapay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/admin'
    | '/dashboard'
    | '/certificates/$code'
    | '/checkout/return'
    | '/courses/$slug'
    | '/admin/orders'
    | '/admin/courses/$id'
    | '/learn/$slug/$lessonId'
    | '/api/public/webhooks/uddoktapay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/courses'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/certificates/$code'
    | '/checkout/return'
    | '/courses/$slug'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/courses/$id'
    | '/_authenticated/learn/$slug/$lessonId'
    | '/api/public/webhooks/uddoktapay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  CertificatesCodeRoute: typeof CertificatesCodeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicWebhooksUddoktapayRoute: typeof ApiPublicWebhooksUddoktapayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$code': {
      id: '/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/certificates/$code'
      preLoaderRoute: typeof CertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/uddoktapay': {
      id: '/api/public/webhooks/uddoktapay'
      path: '/api/public/webhooks/uddoktapay'
      fullPath: '/api/public/webhooks/uddoktapay'
      preLoaderRoute: typeof ApiPublicWebhooksUddoktapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$slug/$lessonId': {
      id: '/_authenticated/learn/$slug/$lessonId'
      path: '/learn/$slug/$lessonId'
      fullPath: '/learn/$slug/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearnSlugLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminCoursesIdRoute: AuthenticatedAdminCoursesIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnSlugLessonIdRoute: typeof AuthenticatedLearnSlugLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnSlugLessonIdRoute: AuthenticatedLearnSlugLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  CertificatesCodeRoute: CertificatesCodeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicWebhooksUddoktapayRoute: ApiPublicWebhooksUddoktapayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
